# Background and foreground colors
background = #06100c
foreground = #d6c9b1

# Standard colors
palette = 0=#06100c
palette = 1=#85795f
palette = 2=#6f806d
palette = 3=#9d917a
palette = 4=#9ba4bb
palette = 5=#857961
palette = 6=#83a2a3
palette = 7=#d6c9b1

# Bright colors
palette = 8=#616865
palette = 9=#aa9e7b
palette = 10=#91a58c
palette = 11=#c3b798
palette = 12=#c0c9e7
palette = 13=#aa9d7e
palette = 14=#a5c9ca
palette = 15=#eed59b
