background            #06100c
foreground            #d6c9b1

# black
color0  #06100c
color8  #616865

# red
color1  #85795f
color9  #aa9e7b

# green
color2  #6f806d
color10 #91a58c

# yellow
color3  #9d917a
color11 #c3b798

# blue
color4  #9ba4bb
color12 #c0c9e7

# magenta
color5  #857961
color13 #aa9d7e

#cyan
color6  #83a2a3
color14 #a5c9ca

#white
color7  #d6c9b1
color15 #eed59b


